# Generated by Django 4.1.4 on 2023-03-11 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(max_length=200, null=True, verbose_name="name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=200, null=True, verbose_name="name"),
                ),
                (
                    "ultimate",
                    models.BooleanField(
                        default=False,
                        help_text="whether can be used as the category of an ad",
                        verbose_name="ultimate",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="categories.category",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("parent"),
                name="parent_and_case_unified_name_unique_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("parent", None)),
                name="unique_case_unified_root_name",
            ),
        ),
    ]
